/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ChrisLee (https://sketchfab.com/chrisleeX)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/frieza-0a828118ada84e66a61987d56de44a06
Title: Frieza
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Frieza(props) {
    const { nodes, materials } = useGLTF('/models/frieza.glb')
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.005}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group
                        position={[-186.535, -77.091, 162.179]}
                        rotation={[-2.442, -0.156, -3.059]}
                        scale={0.42}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Icosphere652_Base_0.geometry}
                            material={materials.Base}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Icosphere652_Base_0_1.geometry}
                            material={materials.Base}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Icosphere652_Base_0_2.geometry}
                            material={materials.Base}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Icosphere652_Base_0_3.geometry}
                            material={materials.Base}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.ZBrush_defualt_group_Base_0.geometry}
                        material={materials.Base}
                        position={[0, -354.888, -113.072]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Group16115_freezer_0.geometry}
                        material={materials.freezer}
                        scale={100}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/frieza.glb');

export default Frieza;
