/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

function Gohan(props) {

    const gohanRef = useRef();

    useFrame(() => {
        gohanRef.current.rotation.y += 0.01;
    })

    const { nodes, materials } = useGLTF('/models/Gohan HD.glb')
    return (
        <group {...props} dispose={null} ref={gohanRef}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['tripo_node_f6de4501-5de1-4f75-aceb-d215315d8dec'].geometry}
                material={materials['tripo_material_f6de4501-5de1-4f75-aceb-d215315d8dec']}
            />
        </group>
    )
}

useGLTF.preload('/models/Gohan HD.glb')

export default Gohan;
