/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Goku(props) {
    const { nodes, materials } = useGLTF('/models/Goku HD.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['tripo_node_4731180c-ddbb-4107-a48b-1539800ecd3c'].geometry}
                material={materials['tripo_material_4731180c-ddbb-4107-a48b-1539800ecd3c']}
            />
        </group>
    )
}

useGLTF.preload('/models/Goku HD.glb')

export default Goku;



